name: musix
description: Music App

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zing_mp3_api:
    git:
      url: https://github.com/thinhhja2001/zingmp3_api
      ref: master


  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  email_validator: ^2.1.17
  intl: ^0.18.0
  palette_generator: ^0.3.3+2
  logging: ^1.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  chewie: ^1.3.6
  video_player: ^2.4.10
  material_design_icons_flutter: ^6.0.7096
  just_audio: ^0.9.31
  percent_indicator: ^4.2.2
  audio_video_progress_bar: ^1.0.0
  get_it: ^7.2.0
  audio_service: ^0.18.9
  flutter_lyric: ^2.0.4+6
  http: ^0.13.5
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/images/

  fonts:
     - family: SVN-Gotham
       fonts:
         - asset: assets/fonts/Gotham/400.otf
         - asset: assets/fonts/Gotham/400I.otf
           style: italic
         - asset: assets/fonts/Gotham/700.otf
           weight: 700
         - asset: assets/fonts/Gotham/700I.otf
           weight: 700
           style: italic
         - asset: assets/fonts/Gotham/300.otf
           weight: 300
         - asset: assets/fonts/Gotham/300I.otf
           weight: 300
           style: italic
