// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFai9yueWwqcJelRtCzbxNFptGmr4OcI',
    appId: '1:449603757021:web:889c8457c8fd7ff7748c34',
    messagingSenderId: '449603757021',
    projectId: 'musix-dc275',
    authDomain: 'musix-dc275.firebaseapp.com',
    storageBucket: 'musix-dc275.appspot.com',
    measurementId: 'G-YLD8GM9BSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKShQnpZ-1eMsrEpzXxDOlS5cLC1nO2nc',
    appId: '1:449603757021:android:0e763dd605952318748c34',
    messagingSenderId: '449603757021',
    projectId: 'musix-dc275',
    storageBucket: 'musix-dc275.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvumTiz2DUVL2RKjK87SinCYQgnTqCMXg',
    appId: '1:449603757021:ios:d25bc7565b52cd5e748c34',
    messagingSenderId: '449603757021',
    projectId: 'musix-dc275',
    storageBucket: 'musix-dc275.appspot.com',
    iosClientId: '449603757021-hg5erefv36ogu9am564c80278e5jbtao.apps.googleusercontent.com',
    iosBundleId: 'com.example.musix',
  );
}
